spring:
  datasource:
    url: jdbc:mysql:///lvyou?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
logging:
  level:
    root: info

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true